package com.prototype.hibernate.model

import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp
import java.time.LocalDateTime
import java.util.*
import javax.persistence.Column
import javax.persistence.GeneratedValue
import javax.persistence.Id
import javax.persistence.MappedSuperclass

/**
 * This class defines the properties common to all of our entities.
 *
 * The following properties are autogenerated:
 * - uuid
 * - createdAt
 * - updatedAt
 *
 * As these properties are generated when the entity is persisted to the database there is no need for us to provide
 * these values when creating new instances of our entities.
 */
@MappedSuperclass
open class BaseEntity {

    @Id
    @GeneratedValue
    @Column(
        unique = true,
        nullable = false
    )
    val uuid : UUID? = null

    @CreationTimestamp
    val createdAt : LocalDateTime? = null

    @UpdateTimestamp
    val updatedAt : LocalDateTime? = null

}
